### ISSUE TITLE
add digitalRead / digitalWrite for 4 sensors

### ISSUE THREAD

**Issue by todocono** [jieyouxu/koding-kreators-mblock-extension#2]
Either "DIGITAL" block with 2 options (sensor1/2/3/4) and OUT/IN, or 8 blocks that say digitalRead digitalWrite with the right pin number (13, 12, 5, 6)

**Comment by jieyouxu** [comment]
Due to the limitation of mBlock 3, it is not possible to have a block which simultaneously reads/writes.

Would it work if I create two blocks:
1. `read digital pin #${n}`, where `${n}` is one of the four digital pins (1, 2, 3, 4), returns `HIGH` (`1`) or `LOW` (`0`).
2. `set digital pin #${n} to ${d}`, where `${n}` is one of the four digital pins (1, 2, 3, 4) and `${d}` is either `HIGH` (`1`) or `LOW` (`0`).

Also not sure about the wording; should it be `pin` or `sensor`?

**Comment by todocono** [comment]
Ah, it makes a lot of sense! I think the best for pedagogic use would be:

DIGITAL Read (sensor1 to 4 menu)
DIGITAL Write (sensor1 to 4 menu)
ANALOG Read (sensor1 to 4 menu)

**Comment by jieyouxu** [comment]
I looked at the schematic again; it would appear that the four sensors (sensor 1, sensor 2, sensor 3 and sensor 4) are mapped by:

| Sensor Number | Digital Pin Number |
| ------------- | ------------------ |
| Sensor 1      | D13                |
| Sensor 2      | D12                |
| Sensor 3      | D5                 |
| Sensor 4      | D4                 |

These mappings are currently being used by the [1.4.0 release](https://github.com/jieyouxu/koding-kreators-mblock-extension/releases/tag/V1.4.0); they did work when I tested them, but could be due to interference.

**Comment by jieyouxu** [comment]
If any problems are discovered in use, a new issue should be opened.
